// set the moment series data
function conflictData() {
  return [
    ["1755/01/01", "(Approx.) Beginning of the Great Upheaval for Acadians that ends in 1763 with 2/3 of Acadians deported"],
    ["1759/09/13", "Battle of the Plains of Abraham near Quebec City.\n- The British defeat the French which marks the end of France's empire in America.\n- The commanders of both armies James Wolfe & Marquis de Montcalm are killed."],
    ["1812/06/18", "The United States launch an invasion of Canada"],
    ["1812/08/16", "Major-General Sir Isaac Brock captures Detroit"],
    ["1812/08/16", "Major-General Sir Isaac Brock dies defending against an American attack at Queenston Heights, Niagara Falls"],
    ["1813/04/29", "The Americans burn the Government house and Parliament buildings in York (now Toronto)"],
    ["1813/06/21", "Laura Secord (pioneer wife and mother of five) makes a dangerous 32 km journey on foot to warn lieutenant James Fitz Gibbon of a planned American attack.\nHer bravery contributed to the Canadian victory at the battle of Beaver Dams 3 days later."],
    ["1813/10/26", "Lieutenant-Colonel Charles de Salaberry turns back 4000 American invaders at Chateauguay, South of Montréal"],
    ["1814/08/24", "Major-General Robert Ross leads an expedition from Nova Scotia and burns down the White house and other public buildings in Washington"],
    ["1814/10/01", "The Duke of Wellington sent some of his best soldiers to defend Canada.\n* He chose Ottawa (Bytown) as endpoint of Rideau Canal, the network of forts to prevent the US from invading Canada again."],
    ["1814/12/24", "The American attempt to conquer Canada has failed.\n* Present day Canada-US border is partly an outcome of the war of 1812, which ensured that Canada would remain independent of the US"],
    ["1837/12/07", "An armed rebellion occurs in the area outside of Montreal and Toronto with too little public support to succeed\n* British troops and Canadian volunteers defeat the rebellion"],
    ["1869/11/02", "Louis Riel from Manitoba leads an army uprising and seizes Fort Garry (Territorial Capital)"],
    ["1885/03/26", "Riel leads a second rebellion in Saskatchewan along Gabriel Dumont"],
    ["1885/05/15", "Riel is captured"],
    ["1899/10/11", "Over 7,000 volunteers fight in the Second Boer War in South Africa till 1902"],
    ["1914/08/04", "Canada enters World War I\n- 600,000 Canadians, mostly volunteers, serve in the war out of a population of 8 million"],
    ["1917/04/12", "The Canadian Corps captures Vimy Ridge, securing the Canadian reputation for valour as the \"shock troops of the British Empire\"\n- April 9th, the beginning of the battle, is now known as Vimy day\n- General Sir Arthur Currie, as the commander of the Canadian Corps, is considered to be Canada's greatest soldier"],
    ["1918/08/08", "Canada is victorious at the Battle of Amiens which is considered as \"the Black day of the German Army\""],
    ["1918/11/11", "Armistice\n- 60,000 Canadians were killed, 170,000 wounded.\n- November 11 eventually becomes Remembrance day."],
    ["1939/09/01", "Beginning of World War II\n* The Royal Canadian Navy (RCN) saw its finest hour in the Battle of the Atlantic protecting convoys of merchant ships against German submarines"],
    ["1940/07/10", "The Royal Canadian Air Force (RCAF) takes part in the Battle of England.\n* The RCAF provides a high portion of Commonwealth aircrew in bombers and fighter planes over Europe."],
    ["1944/06/06", "D-Day, invasion of Normandy\n* 15,000 Canadian troops captune Juno beach"],
    ["1945/09/02", "End of World War II\n* More than 1 million Canadians and Newfoundlanders served in Wolrd War II"],
  ]
}
function momentData() {
  return [
    ["1497/01/01", "European exploration begins"],
    ["1497/01/01", "John Cabot Draws first map of East Coast"],
    ["1534/01/01", "- Jacques Cartier makes 3 voyages across the Atlantic over 8 years, and claims land for Francis I, King of France.\n- He is the 1st to explore the St Lawrance river and see Montréal and Quebec\n- Jacques Cartier hears 2 captured guides speak the Iroquoian word \"kanata\", meaning \"village\""],
    ["1550/01/01", "(Approx.) \"Canada\" starts appearing on maps"],
    ["1604/01/01", "Acadians begin settling in the Maritime provinces"],
    ["1608/07/03", "Samuel de Champlain builds the 1st fortress in Quebec City"],
    ["1670/05/02", "King Charles III of England grants the Hudson's Bay Company exclusive trading rights"],
    ["1701/08/04", "French and Iroquois make peace"],
    ["1758/05/20", "First representative assembly in Halifax"],
    ["1763/10/07", "Royal proclamation by King George III:\n- Britain renames the colony \"Province of Quebec\"\n- Territorial rights are guaranteed to aboriginal people"],
    ["1773/07/07", "First representative assembly in PEI"],
    ["1774/06/22", "Quebec Act passed by the British Parliament:\n- Religious freedom allowed for French catholics\n- French catholics are permitted to hold public office\n- The French civil law is restored while the British criminal law is maintained"],
    ["1776/07/04", "The 13 British colonies south of Quebec declare their independence and form the United States\n- Loyalists flee the oppression and move to Nova Scotia and Quebec\n- Joseph Brant leads thousands of loyalist Mohawk indians to Canada"],
    ["1785/11/01", "First representative assembly in New Brunswick"],
    ["1791/12/26", "Constitutional act:\n- Divides the Province of Quebec to Upper Canada (Ontario) and Lower Canada (Quebec)\n- Grants first legislative assemblies elected by the people\n-Official names the land Canada"],
    ["1792/01/15", "Black Nova Scotians who were given poor lang move to Sierra Leone to establish Freetown"],
    ["1793/01/21", "The first Assembly of Lower Canada debates whether to use both French and English"],
    ["1793/07/09", "Upper Canada, led by Lieutenant Governor John Graves Simcoe, becomes the first province in the Empire to move towards abolition"],
    ["1807/03/25", "The British Parliament prohibits buying and selling of slaves"],
    ["1832/03/30", "The Montreal Stock Exchange opens"],
    ["1839/02/11", "Lord Durham, an English reformer, recommends that Upper and Lower Canada be merged and given responsible government"],
    ["1840/07/23", "Upper and Lower Canada are united into the Province of Canada.\n* Sir Louis-Hippolyte Lafontaine, Robert Baldwin and Joseph Howe work with British governors towards responsible government"],
    ["1848/01/25", "Nova Scotia is the first North American colony to attain full responsible government"],
    ["1849/02/27", "The governor of United Canada, Lorg Egin, introduces a responsible government\nLafontaine, a champion of democracy and French language rights, becomes the first leader of a responsible government in the Canadas"],
    ["1850/01/01", "During the 1850s, the maple lead starts appearing on Canadian uniforms & insignia"],
    ["1864/09/01", "The Charlottetown Conference marks the beginning of the Confederation of Canada which is completed in 1867.\n- Representatives from Nova Scotia, New Brunswick and Province of Canada form a new country.\n- Federal and provincial governments are created.\n- Province of Canada is split into Ontarioa & Quebec\n- Sir George-Etienne Cartier, a key architect of Confederation from Québec, leads Quebec into confederation."],
    ["1867/07/01", "The Birtish North America Act is enacted\n- The Dominion of Canada is born, term used for 100 years.\nJuly 1st is referred to as \"Dominion Day\" till 1982"],
    ["1867/07/01", "Sir John Alexander MacDonald is Canada's 1st Prime Minister and a father of Confederation.\n- January 11th is Sir John A. Macdonald day.\n- His portrait is on the $10 bill."],
    ["1870/05/12", "Canada establishes the new province of Manitoba"],
    ["1870/09/02", "Louis Riel flees to the US"],
    ["1871/07/20", "BC joins Canada after Ottawa promises to build a railway to the West Coast"],
    ["1873/05/23", "John A. Macdonald establishes the North West Mounted Police (NWMP) to pacify the West.\n- One of Canada's most colourful heroes, General Sir Sam Steele, comes from the ranks of the mounties"],
    ["1873/07/01", "Prince Edward Island joins Canada"],
    ["1880/09/01", "Transfer of the Artic Islands from Britain to the North West Territories"],
    ["1885/07/20", "The Chinese Immigration Act imposes the Head Tax, a race-based entry fee, to chinese immigrants.\n- The Government of Canada apologizes in 2006."],
    ["1885/11/07", "The Canadian Pacific Ralway's \"Ribbons of steel\" is completed"],
    ["1885/11/16", "Riel is executed after he was found guilty of treason despite the opposition of Québec"],
    ["1896/07/11", "Wilfrid Laurier becomes the 1st French Canadian Prime Minister and holds the longest unbroken term of office with 15 years"],
    ["1898/06/13", "Yukon Territory joins Canada"],
    ["1905/09/01", "Alberta & Saskatchewan join Canada"],
    ["1918/05/24", "With the Women's Franchise Act, most Canadian women aged 21 and over are granted the right to vote in federal elections"],
    ["1921/12/06", "Agnes Macphail, a farmer and teacher, becomes the 1st woman MP"],
    ["1927/03/07", "The Old Age Security (pre-pension plan) is devised."],
    ["1929/10/29", "The stock market crashes leading to the Great Recession."],
    ["1933/06/01", "Unemployment reaches 27% an many businesses are wipedout."],
    ["1939/06/07", "Jews trying to flee Nazi Germany are turned away."],
    ["1940/08/07", "Unemployment insurance (now EI) is introduced by Federal government."],
    ["1940/04/25", "Quebec grants women the right to vote."],
    ["1949/03/31", "Newfoundland and Labrador join Canada"],
    ["1949/04/04", "Canada joins with other countries of the West to form a military alliance: The North Atlantic Treaty Organization, or NATO."],
    ["1957/08/01", "Canada joins with the US and forms the North American Aerospace Defence Command, or NORAD."],
    ["1960/06/22", "Beginning of the Quiet Revolution in Québec: an era of rapid change."],
    ["1963/07/19", "Parliament establishes the Royal Commission on Bilingualism and Biculturalism"],
    ["1969/09/09", "Official Languages Act guaranteeing French and English services in the Federal government across Canada"],
    ["1970/03/20", "Canada helps found La Francophonie, an international association of French-speaking countries"],
    ["1980/05/20", "Referendum of Quebec path toward sovereignty is defeated"],
    ["1982/03/29", "The Constitution of Canada is amended to entrench the Canadian Charter of Rights and Freedoms.\n- Quebec didn't provide agreement"],
    ["1995/10/30", "Second Referendum on Quebec's sovereignty is defeated"],
    ["2006/11/27", "The House of Commons recognize that the Québécois form a nation"],
  ];
}
