// set the moment series data
function historicalData() {
  return {
    "groups": [
      {
        "title": "Conflicts",
        "emoji": "💥",
        "events": [
          {"date": "1755", "title": "Beginning of the Great Upheaval for Acadians that ends in 1763 with 2/3 of Acadians deported"},
          {"date": "1759-09-13", "title": "Battle of the Plains of Abraham near Quebec City.", "description": ["The British defeat the French which marks the end of France's empire in America.", "The commanders of both armies James Wolfe & Marquis de Montcalm are killed."]},
          {"date": "1812-06-18", "title": "The United States launch an invasion of Canada"},
          {"date": "1812-08-16", "title": "Major-General Sir Isaac Brock captures Detroit"},
          {"date": "1812-08-16", "title": "Major-General Sir Isaac Brock dies defending against an American attack at Queenston Heights, Niagara Falls"},
          {"date": "1813-04-29", "title": "The Americans burn the Government house and Parliament buildings in York (now Toronto)"},
          {"date": "1813-06-21", "title": "Laura Secord (pioneer wife and mother of five) makes a dangerous 32 km journey on foot to warn lieutenant James Fitz Gibbon of a planned American attack.", "description": "Her bravery contributed to the Canadian victory at the battle of Beaver Dams 3 days later."},
          {"date": "1813-10-26", "title": "Lieutenant-Colonel Charles de Salaberry turns back 4000 American invaders at Chateauguay, South of Montreal"},
          {"date": "1814-08-24", "title": "Major-General Robert Ross leads an expedition from Nova Scotia and burns down the White house and other public buildings in Washington"},
          {"date": "1814-10-01", "title": "The Duke of Wellington sent some of his best soldiers to defend Canada.", "description": "He chose Ottawa (Bytown) as endpoint of Rideau Canal, the network of forts to prevent the US from invading Canada again."},
          {"date": "1814-12-24", "title": "The American attempt to conquer Canada has failed.", "description": "Present day Canada-US border is partly an outcome of the war of 1812, which ensured that Canada would remain independent of the US"},
          {"date": "1837-12-07", "title": "An armed rebellion occurs in the area outside of Montreal and Toronto with too little public support to succeed" ,"description": "British troops and Canadian volunteers defeat the rebellion"},
          {"date": "1869-11-02", "title": "Louis Riel from Manitoba leads an army uprising and seizes Fort Garry (Territorial Capital)"},
          {"date": "1885-03-26", "title": "Riel leads a second rebellion in Saskatchewan along Gabriel Dumont"},
          {"date": "1885-05-15", "title": "Riel is captured"},
          {"date": "1899-10-11", "title": "Over 7,000 volunteers fight in the Second Boer War in South Africa till 1902"},
          {"date": "1914-08-04", "title": "Canada enters World War I", "description": "600,000 Canadians, mostly volunteers, serve in the war out of a population of 8 million"},
          {"date": "1917-04-12", "title": "The Canadian Corps captures Vimy Ridge, securing the Canadian reputation for valour as the \"shock troops of the British Empire\"", "description": ["April 9th, the beginning of the battle, is now known as Vimy day", "General Sir Arthur Currie, as the commander of the Canadian Corps, is considered to be Canada's greatest soldier"]},
          {"date": "1918-08-08", "title": "Canada is victorious at the Battle of Amiens which is considered as \"the Black day of the German Army\""},
          {"date": "1918-11-11", "title": "World Ward II Armistice", "description": ["60,000 Canadians were killed, 170,000 wounded.", "November 11 eventually becomes Remembrance day."]},
          {"date": "1939-09-01", "title": "Beginning of World War II", "description": "The Royal Canadian Navy (RCN) saw its finest hour in the Battle of the Atlantic protecting convoys of merchant ships against German submarines"},
          {"date": "1940-07-10", "title": "The Royal Canadian Air Force (RCAF) takes part in the Battle of England", "description": "The RCAF provides a high portion of Commonwealth aircrew in bombers and fighter planes over Europe."},
          {"date": "1944-06-06", "title": "D-Day, invasion of Normandy", "description": "15,000 Canadian troops captune Juno beach"},
          {"date": "1945-09-02", "title": "End of World War II", "description": "More than 1 million Canadians and Newfoundlanders served in Wolrd War II"},
        ]
      },
      {
        "title": "Legal",
        "emoji": "📜",
        "events": [
          {"date": "1670-05-02", "title": "King Charles III of England grants the Hudson's Bay Company exclusive trading rights"},
          {"date": "1758-05-20", "title": "First representative assembly in Halifax"},
          {"date": "1763-10-07", "title": "Royal proclamation by King George III", "description": ["Britain renames the colony \"Province of Quebec\"", "Territorial rights are guaranteed to aboriginal people"]},
          {"date": "1773-07-07", "title": "First representative assembly in PEI"},
          {"date": "1774-06-22", "title": "Quebec Act passed by the British Parliament", "description": ["Religious freedom allowed for French catholics", "French catholics are permitted to hold public office", "The French civil law is restored while the British criminal law is maintained"]},
          {"date": "1785-11-01", "title": "First representative assembly in New Brunswick"},
          {"date": "1791-12-26", "title": "Constitutional act", "description": ["Divides the Province of Quebec to Upper Canada (Ontario) and Lower Canada (Quebec)", "Grants first legislative assemblies elected by the people\n-Official names the land Canada"]},
          {"date": "1793-07-09", "title": "Upper Canada, led by Lieutenant Governor John Graves Simcoe, becomes the first province in the Empire to move towards abolition"},
          {"date": "1807-03-25", "title": "The British Parliament prohibits buying and selling of slaves"},
          {"date": "1840-07-23", "title": "Upper and Lower Canada are united into the Province of Canada.", "description": "Sir Louis-Hippolyte Lafontaine, Robert Baldwin and Joseph Howe work with British governors towards responsible government"},
          {"date": "1848-01-25", "title": "Nova Scotia is the first North American colony to attain full responsible government"},
          {"date": "1849-02-27", "title": "The governor of United Canada, Lorg Egin, introduces a responsible government", "description": "Lafontaine, a champion of democracy and French language rights, becomes the first leader of a responsible government in the Canadas"},
          {"date": "1864-09-01", "title": "The Charlottetown Conference marks the beginning of the Confederation of Canada which is completed in 1867.", "description": ["Representatives from Nova Scotia, New Brunswick and Province of Canada form a new country.", "Federal and provincial governments are created.", "Province of Canada is split into Ontario & Quebec", "Sir George-Etienne Cartier, a key architect of Confederation from Quebec, leads Quebec into confederation."]},
          {"date": "1867-07-01", "title": "The Birtish North America Act is enacted", "description": ["The Dominion of Canada is born, term used for 100 years.", "July 1st is referred to as \"Dominion Day\" till 1982"]},
          {"date": "1870-05-12", "title": "Canada establishes the new province of Manitoba"},
          {"date": "1871-07-20", "title": "BC joins Canada after Ottawa promises to build a railway to the West Coast"},
          {"date": "1873-05-23", "title": "John A. Macdonald establishes the North West Mounted Police (NWMP) to pacify the West", "description": "One of Canada's most colourful heroes, General Sir Sam Steele, comes from the ranks of the mounties"},
          {"date": "1873-07-01", "title": "Prince Edward Island joins Canada"},
          {"date": "1880-09-01", "title": "Transfer of the Artic Islands from Britain to the North West Territories"},
          {"date": "1885-07-20", "title": "The Chinese Immigration Act imposes the Head Tax, a race-based entry fee, to chinese immigrants", "description": "The Government of Canada apologizes in 2006."},
          {"date": "1898-06-13", "title": "Yukon Territory joins Canada"},
          {"date": "1905-09-01", "title": "Alberta & Saskatchewan join Canada"},
          {"date": "1918-05-24", "title": "With the Women's Franchise Act, most Canadian women aged 21 and over are granted the right to vote in federal elections"},
          {"date": "1927-03-07", "title": "The Old Age Security (pre-pension plan) is devised."},
          {"date": "1940-08-07", "title": "Unemployment insurance (now EI) is introduced by Federal government."},
          {"date": "1940-04-25", "title": "Quebec grants women the right to vote."},
          {"date": "1949-03-31", "title": "Newfoundland and Labrador join Canada"},
          {"date": "1963-07-19", "title": "Parliament establishes the Royal Commission on Bilingualism and Biculturalism"},
          {"date": "1969-09-09", "title": "Official Languages Act guaranteeing French and English services in the Federal government across Canada"},
          {"date": "1982-03-29", "title": "The Constitution of Canada is amended to entrench the Canadian Charter of Rights and Freedoms", "description": "Quebec didn't provide agreement"},
          {"date": "2006-11-27", "title": "The House of Commons recognize that the Quebecois form a nation"},
        ]
      },
      {
        "title": "Misc. events",
        "events": [
          {"date": "1497", "title": "European exploration begins", "description": "John Cabot Draws first map of East Coast", "emoji": "🧭"},
          {"date": "1534", "title": "Jacques Cartier makes 3 voyages across the Atlantic over 8 years, and claims land for Francis I, King of France.", "description": ["He is the 1st to explore the St Lawrance river and see Montreal and Quebec", "Jacques Cartier hears 2 captured guides speak the Iroquoian word \"kanata\", meaning \"village\""], "emoji": "⚜️"},
          {"date": "1550", "title": "\"Canada\" starts appearing on maps", "emoji": "🗺️"},
          {"date": "1604", "title": "Acadians begin settling in the Maritime provinces", "emoji": "⚓"},
          {"date": "1608-07-03", "title": "Samuel de Champlain builds the 1st fortress in Quebec City", "emoji": "⚜️"},
          {"date": "1701-08-04", "title": "French and Iroquois make peace", "emoji": "🤝"},
          {"date": "1776-07-04", "title": "The 13 British colonies south of Quebec declare their independence and form the United States", "description": ["Loyalists flee the oppression and move to Nova Scotia and Quebec", "Joseph Brant leads thousands of loyalist Mohawk indians to Canada"], "emoji": "🇺🇲"},
          {"date": "1792-01-15", "title": "Black Nova Scotians who were given poor lang move to Sierra Leone to establish Freetown", "emoji": "🇸🇱"},
          {"date": "1793-01-21", "title": "The first Assembly of Lower Canada debates whether to use both French and English", "emoji": "🗣️"},
          {"date": "1832-03-30", "title": "The Montreal Stock Exchange opens", "emoji": "💱"},
          {"date": "1839-02-11", "title": "Lord Durham, an English reformer, recommends that Upper and Lower Canada be merged and given responsible government", "emoji": "🔗"},
          {"date": "1850-01-01", "title": "During the 1850s, the maple lead starts appearing on Canadian uniforms & insignia", "emoji": "🍁"},
          {"date": "1867-07-01", "title": "Sir John Alexander MacDonald is Canada's 1st Prime Minister and a father of Confederation.", "description": ["January 11th is Sir John A. Macdonald day.", "His portrait is on the $10 bill."], "emoji": "1️⃣"},
          {"date": "1870-09-02", "title": "Louis Riel flees to the US", "emoji": "🏃🏻‍♂️"},
          {"date": "1885-11-07", "title": "The Canadian Pacific Ralway's \"Ribbons of steel\" is completed", "emoji": "🛤️"},
          {"date": "1885-11-16", "title": "Riel is executed after he was found guilty of treason despite the opposition of Quebec", "emoji": "💀"},
          {"date": "1896-07-11", "title": "Wilfrid Laurier becomes the 1st French Canadian Prime Minister", "description": "He holds the longest unbroken term of office with 15 years", "emoji": "1️⃣"},
          {"date": "1921-12-06", "title": "Agnes Macphail, a farmer and teacher, becomes the 1st woman MP", "emoji": "🗳️"},
          {"date": "1929-10-29", "title": "The stock market crashes leading to the Great Recession.", "emoji": "📉"},
          {"date": "1933-06-01", "title": "Unemployment reaches 27% an many businesses are wipedout.", "emoji": "📉"},
          {"date": "1939-06-07", "title": "Jews trying to flee Nazi Germany are turned away.", "emoji": "🛂"},
          {"date": "1949-04-04", "title": "Canada joins with other countries of the West to form a military alliance: The North Atlantic Treaty Organization, or NATO.", "emoji": "🤝"},
          {"date": "1957-08-01", "title": "Canada joins with the US and forms the North American Aerospace Defence Command, or NORAD.", "emoji": "🤝"},
          {"date": "1960-06-22", "title": "Beginning of the Quiet Revolution in Quebec: an era of rapid change.", "emoji": "✊"},
          {"date": "1970-03-20", "title": "Canada helps found La Francophonie, an international association of French-speaking countries", "emoji": "🗣"},
          {"date": "1980-05-20", "title": "Referendum of Quebec path toward sovereignty is defeated", "emoji": "🗳️"},
          {"date": "1995-10-30", "title": "Second Referendum on Quebec's sovereignty is defeated", "emoji": "🗳️"},
        ]
      }
    ]
  }
}
